// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsAa6nuS7jkQy4zTIXEx8VsUyRMPJodzo',
    appId: '1:509142964902:web:47d173760c27834e637267',
    messagingSenderId: '509142964902',
    projectId: 'my-zakat',
    authDomain: 'my-zakat.firebaseapp.com',
    storageBucket: 'my-zakat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUrF-73yx4KVFvQMiULbVO_FApa376Wlg',
    appId: '1:509142964902:android:da57ae058696c489637267',
    messagingSenderId: '509142964902',
    projectId: 'my-zakat',
    storageBucket: 'my-zakat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN8XIb8xLWr8GLevS6zBcPYJAm7L4A2ns',
    appId: '1:509142964902:ios:5e63cd79d4c07628637267',
    messagingSenderId: '509142964902',
    projectId: 'my-zakat',
    storageBucket: 'my-zakat.appspot.com',
    iosBundleId: 'com.example.adminApplicationZakat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN8XIb8xLWr8GLevS6zBcPYJAm7L4A2ns',
    appId: '1:509142964902:ios:924fe35cb146bb48637267',
    messagingSenderId: '509142964902',
    projectId: 'my-zakat',
    storageBucket: 'my-zakat.appspot.com',
    iosBundleId: 'com.example.adminApplicationZakat.RunnerTests',
  );
}
